blank_issues_enabled: false
contact_links:
  - name: Join Notion CN Community
    url: https://t.me/Notionso
    about: Ask and discuss Notion and Nobelium with other community members.
waline:
  visitor: true   # 文章访问量统计
  lang: zh-CN     # 语言，默认zh-CN
  login: enable   # 登录模式状态，默认值enable，force可以强制登录
  wordLimit: 0    # 评论字数限制，0为不限制，默认值为0
  pageSize: 10    # 评论列表分页，数字为条数，默认值10
  highlight: true # 代码高亮，默认true
  meta: ['nick', 'mail', 'link'] # 评论者相关属性，默认['nick', 'mail', 'link']
  requiredMeta: ['nick', 'mail'] #设置评论者属性必填项，默认[]（即匿名）
  placeholder: '何事沉吟？' # 评论框占位提示符，默认'欢迎评论'
  copyright: false # 是否显示页脚版权信息
  emoji: [
    'https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/tw-emoji',
    'https://cdn.jsdelivr.net/gh/norevi/waline-blobcatemojis@1.0/blobs',
    'https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/bilibili',
  ] # 自定义表情包
